/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naloga4;

/**
 *
 * @author tilen
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLayeredPaneAvtomobil = new javax.swing.JLayeredPane();
        jLabelDatumIzposoje = new javax.swing.JLabel();
        jLabelDatumOddaje = new javax.swing.JLabel();
        jLabelPrevzemnoMesto = new javax.swing.JLabel();
        jLabelMestoOddaje = new javax.swing.JLabel();
        jLabelVelikostAvtomobila = new javax.swing.JLabel();
        jComboBoxPrevzemnoMesto = new javax.swing.JComboBox<>();
        jComboBoxMestoOddaje = new javax.swing.JComboBox<>();
        jRadioButtonVelikostMajhen = new javax.swing.JRadioButton();
        jRadioButtonVelikostSrednji = new javax.swing.JRadioButton();
        jRadioButtonVelikostVelik = new javax.swing.JRadioButton();
        jLabelIzbiraAvtomobila = new javax.swing.JLabel();
        jComboBoxIzbiraAvtomobila = new javax.swing.JComboBox<>();
        jLabelIzbiraMenjalnika = new javax.swing.JLabel();
        jLabelVrstaMotorja = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jRadioButtonMenjalnikAvtomatski = new javax.swing.JRadioButton();
        jRadioButtonMenjalnikRočni = new javax.swing.JRadioButton();
        jRadioButtonMotorDizelski = new javax.swing.JRadioButton();
        jRadioButtonMotorBencinski = new javax.swing.JRadioButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLayeredPaneOseba = new javax.swing.JLayeredPane();
        jLabelImeOsebe = new javax.swing.JLabel();
        jLabelPriimekOsebe = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabelKrajOsebe = new javax.swing.JLabel();
        jLabelUlicaOsebe = new javax.swing.JLabel();
        jLabelTelefonOsebe = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabelStarostOsebe = new javax.swing.JLabel();
        jLabelDodatnoZav = new javax.swing.JLabel();
        jRadioButtonDodatnoDa = new javax.swing.JRadioButton();
        jRadioButtonDodatnoNe = new javax.swing.JRadioButton();
        jSpinnerStarost = new javax.swing.JSpinner();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabelPostnaSt = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabelEposta = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabelIzkusnje = new javax.swing.JLabel();
        jSpinnerIzkusnje = new javax.swing.JSpinner();
        jLayeredPanePlačilo = new javax.swing.JLayeredPane();
        jLabelMoznostPlacila = new javax.swing.JLabel();
        jRadioButtonGotovina = new javax.swing.JRadioButton();
        jRadioButtonKartica = new javax.swing.JRadioButton();
        jButtonIzvediPlacilo = new javax.swing.JButton();
        jLabelStKartice = new javax.swing.JLabel();
        jTextFieldStKartice = new javax.swing.JTextField();
        jLabelCCV = new javax.swing.JLabel();
        jTextFieldCCV = new javax.swing.JTextField();
        jLayeredPaneZnesek = new javax.swing.JLayeredPane();
        jLabelDnesvniZnesek = new javax.swing.JLabel();
        jLabelSkupniZnesek = new javax.swing.JLabel();
        jLabelDnevnaNajemnina = new javax.swing.JLabel();
        jLabelSkupnaNajemnina = new javax.swing.JLabel();
        jButtonPonastavi = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuDatoteka = new javax.swing.JMenu();
        jMenuItemOdpri = new javax.swing.JMenuItem();
        jMenuItemShrani = new javax.swing.JMenuItem();
        jMenuItemIzhod = new javax.swing.JMenuItem();
        jMenuUredi = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuPomoc = new javax.swing.JMenu();
        jMenuItemAvtor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPaneAvtomobil.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki o avtomobilu"));

        jLabelDatumIzposoje.setText("Datum izposoje:");

        jLabelDatumOddaje.setText("Datum oddaje:");

        jLabelPrevzemnoMesto.setText("Prevzemno mesto:");

        jLabelMestoOddaje.setText("Mesto oddaje:");

        jLabelVelikostAvtomobila.setText("Velikost avtomobila:");

        jComboBoxPrevzemnoMesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Murska Sobota", "Jesenice", "Portorož", "letališče Brnik", "letačišče Maribor" }));

        jComboBoxMestoOddaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Murska Sobota", "Jesenice", "Portorož", "letališče Brnik", "letačišče Maribor" }));

        jRadioButtonVelikostMajhen.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonVelikostMajhen.setText("Majhen");

        jRadioButtonVelikostSrednji.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonVelikostSrednji.setText("Srednji");

        jRadioButtonVelikostVelik.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonVelikostVelik.setText("Velik");

        jLabelIzbiraAvtomobila.setText("Izbira avtomobila:");

        jComboBoxIzbiraAvtomobila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelIzbiraMenjalnika.setText("Izbira menjalnika:");

        jLabelVrstaMotorja.setText("Vrsta motorja:");

        jRadioButtonMenjalnikAvtomatski.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonMenjalnikAvtomatski.setText("Avtomatski");

        jRadioButtonMenjalnikRočni.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonMenjalnikRočni.setText("Ročni");

        jRadioButtonMotorDizelski.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonMotorDizelski.setText("Dizelski");

        jRadioButtonMotorBencinski.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonMotorBencinski.setText("Bencinski");

        jLayeredPaneAvtomobil.setLayer(jLabelDatumIzposoje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jLabelDatumOddaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jLabelPrevzemnoMesto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jLabelMestoOddaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jLabelVelikostAvtomobila, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jComboBoxPrevzemnoMesto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jComboBoxMestoOddaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jRadioButtonVelikostMajhen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jRadioButtonVelikostSrednji, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jRadioButtonVelikostVelik, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jLabelIzbiraAvtomobila, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jComboBoxIzbiraAvtomobila, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jLabelIzbiraMenjalnika, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jLabelVrstaMotorja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jComboBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jRadioButtonMenjalnikAvtomatski, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jRadioButtonMenjalnikRočni, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jRadioButtonMotorDizelski, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jRadioButtonMotorBencinski, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jComboBox5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jComboBox6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jComboBox7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jComboBox8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneAvtomobil.setLayer(jComboBox9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneAvtomobilLayout = new javax.swing.GroupLayout(jLayeredPaneAvtomobil);
        jLayeredPaneAvtomobil.setLayout(jLayeredPaneAvtomobilLayout);
        jLayeredPaneAvtomobilLayout.setHorizontalGroup(
            jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAvtomobilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDatumIzposoje)
                    .addGroup(jLayeredPaneAvtomobilLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrevzemnoMesto)
                            .addComponent(jLabelIzbiraMenjalnika)
                            .addComponent(jLabelVrstaMotorja)
                            .addComponent(jLabelIzbiraAvtomobila)
                            .addComponent(jLabelVelikostAvtomobila))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxIzbiraAvtomobila, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPaneAvtomobilLayout.createSequentialGroup()
                                .addComponent(jRadioButtonVelikostMajhen)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonVelikostSrednji)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonVelikostVelik))
                            .addGroup(jLayeredPaneAvtomobilLayout.createSequentialGroup()
                                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jLayeredPaneAvtomobilLayout.createSequentialGroup()
                                        .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonMenjalnikAvtomatski)
                                            .addComponent(jRadioButtonMotorDizelski))
                                        .addGap(18, 18, 18)
                                        .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonMenjalnikRočni)
                                            .addComponent(jRadioButtonMotorBencinski)))
                                    .addGroup(jLayeredPaneAvtomobilLayout.createSequentialGroup()
                                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBoxPrevzemnoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMestoOddaje)
                                    .addComponent(jLabelDatumOddaje))
                                .addGap(24, 24, 24)
                                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxMestoOddaje, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jLayeredPaneAvtomobilLayout.createSequentialGroup()
                                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jLayeredPaneAvtomobilLayout.setVerticalGroup(
            jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneAvtomobilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatumIzposoje)
                    .addComponent(jLabelDatumOddaje)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrevzemnoMesto)
                    .addComponent(jComboBoxPrevzemnoMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMestoOddaje)
                    .addComponent(jComboBoxMestoOddaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVelikostAvtomobila)
                    .addComponent(jRadioButtonVelikostMajhen)
                    .addComponent(jRadioButtonVelikostSrednji)
                    .addComponent(jRadioButtonVelikostVelik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIzbiraAvtomobila)
                    .addComponent(jComboBoxIzbiraAvtomobila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIzbiraMenjalnika)
                    .addComponent(jRadioButtonMenjalnikAvtomatski)
                    .addComponent(jRadioButtonMenjalnikRočni))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneAvtomobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVrstaMotorja)
                    .addComponent(jRadioButtonMotorDizelski)
                    .addComponent(jRadioButtonMotorBencinski))
                .addContainerGap())
        );

        jLayeredPaneOseba.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki o osebi"));

        jLabelImeOsebe.setText("Ime:");

        jLabelPriimekOsebe.setText("Priimek:");

        jLabelKrajOsebe.setText("Kraj:");

        jLabelUlicaOsebe.setText("Ulica:");

        jLabelTelefonOsebe.setText("Telefon:");

        jLabelStarostOsebe.setText("Starost:");

        jLabelDodatnoZav.setText("Dodatno zavarovanje:");

        jRadioButtonDodatnoDa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonDodatnoDa.setText("Da");

        jRadioButtonDodatnoNe.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonDodatnoNe.setText("Ne");

        jLabelPostnaSt.setText("Poštna št.:");

        jLabelEposta.setText("E-pošta:");

        jTextField4.setToolTipText("");

        jLabelIzkusnje.setText("Izkušnje(leta):");

        jLayeredPaneOseba.setLayer(jLabelImeOsebe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jLabelPriimekOsebe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jLabelKrajOsebe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jLabelUlicaOsebe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jLabelTelefonOsebe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jTextField7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jLabelStarostOsebe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jLabelDodatnoZav, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jRadioButtonDodatnoDa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jRadioButtonDodatnoNe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jSpinnerStarost, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jTextField9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jTextField11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jLabelPostnaSt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jLabelEposta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jLabelIzkusnje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneOseba.setLayer(jSpinnerIzkusnje, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneOsebaLayout = new javax.swing.GroupLayout(jLayeredPaneOseba);
        jLayeredPaneOseba.setLayout(jLayeredPaneOsebaLayout);
        jLayeredPaneOsebaLayout.setHorizontalGroup(
            jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneOsebaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPaneOsebaLayout.createSequentialGroup()
                        .addComponent(jLabelDodatnoZav)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDodatnoDa)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDodatnoNe)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPaneOsebaLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImeOsebe)
                            .addComponent(jLabelPriimekOsebe)
                            .addComponent(jLabelTelefonOsebe))
                        .addGap(21, 21, 21)
                        .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStarostOsebe)
                            .addComponent(jLabelUlicaOsebe)
                            .addComponent(jLabelKrajOsebe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9)
                            .addComponent(jSpinnerStarost, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jTextField11))
                        .addGap(49, 49, 49)
                        .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPostnaSt)
                            .addComponent(jLabelEposta)
                            .addComponent(jLabelIzkusnje))
                        .addGap(4, 4, 4)
                        .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jSpinnerIzkusnje))))
                .addContainerGap())
        );
        jLayeredPaneOsebaLayout.setVerticalGroup(
            jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneOsebaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelImeOsebe)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKrajOsebe)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPostnaSt)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPriimekOsebe)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUlicaOsebe)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEposta)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefonOsebe)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStarostOsebe)
                    .addComponent(jSpinnerStarost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIzkusnje)
                    .addComponent(jSpinnerIzkusnje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneOsebaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDodatnoZav)
                    .addComponent(jRadioButtonDodatnoDa)
                    .addComponent(jRadioButtonDodatnoNe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPanePlačilo.setBorder(javax.swing.BorderFactory.createTitledBorder("Plačilo"));

        jLabelMoznostPlacila.setText("Možnost plačila:");

        jRadioButtonGotovina.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonGotovina.setText("Gotovina");

        jRadioButtonKartica.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonKartica.setText("Kartica");

        jButtonIzvediPlacilo.setText("Izvedi plačilo");

        jLabelStKartice.setText("Št. kreditne kartice:");

        jTextFieldStKartice.setText("xxxx-xxxx-xxxx-xxxx");

        jLabelCCV.setText("CCV:");

        jLayeredPaneZnesek.setBorder(javax.swing.BorderFactory.createTitledBorder("Plačilni znesek"));

        jLabelDnesvniZnesek.setText("Dnevni znesek:");

        jLabelSkupniZnesek.setText("Skupni znesek:");

        jLabelDnevnaNajemnina.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelDnevnaNajemnina.setText("Cena dnevne najemnine");

        jLabelSkupnaNajemnina.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabelSkupnaNajemnina.setText("Cena celotne najemnine");

        jLayeredPaneZnesek.setLayer(jLabelDnesvniZnesek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZnesek.setLayer(jLabelSkupniZnesek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZnesek.setLayer(jLabelDnevnaNajemnina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZnesek.setLayer(jLabelSkupnaNajemnina, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneZnesekLayout = new javax.swing.GroupLayout(jLayeredPaneZnesek);
        jLayeredPaneZnesek.setLayout(jLayeredPaneZnesekLayout);
        jLayeredPaneZnesekLayout.setHorizontalGroup(
            jLayeredPaneZnesekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneZnesekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneZnesekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDnesvniZnesek)
                    .addComponent(jLabelSkupniZnesek))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneZnesekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSkupnaNajemnina)
                    .addComponent(jLabelDnevnaNajemnina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneZnesekLayout.setVerticalGroup(
            jLayeredPaneZnesekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneZnesekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneZnesekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDnesvniZnesek)
                    .addComponent(jLabelDnevnaNajemnina))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPaneZnesekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSkupniZnesek)
                    .addComponent(jLabelSkupnaNajemnina))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jButtonPonastavi.setText("Ponastavi");

        jLayeredPanePlačilo.setLayer(jLabelMoznostPlacila, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePlačilo.setLayer(jRadioButtonGotovina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePlačilo.setLayer(jRadioButtonKartica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePlačilo.setLayer(jButtonIzvediPlacilo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePlačilo.setLayer(jLabelStKartice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePlačilo.setLayer(jTextFieldStKartice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePlačilo.setLayer(jLabelCCV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePlačilo.setLayer(jTextFieldCCV, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePlačilo.setLayer(jLayeredPaneZnesek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPanePlačilo.setLayer(jButtonPonastavi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPanePlačiloLayout = new javax.swing.GroupLayout(jLayeredPanePlačilo);
        jLayeredPanePlačilo.setLayout(jLayeredPanePlačiloLayout);
        jLayeredPanePlačiloLayout.setHorizontalGroup(
            jLayeredPanePlačiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPanePlačiloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPanePlačiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPanePlačiloLayout.createSequentialGroup()
                        .addGroup(jLayeredPanePlačiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPaneZnesek)
                            .addGroup(jLayeredPanePlačiloLayout.createSequentialGroup()
                                .addGroup(jLayeredPanePlačiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jLayeredPanePlačiloLayout.createSequentialGroup()
                                        .addComponent(jLabelMoznostPlacila)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRadioButtonGotovina)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonKartica)
                                        .addGap(53, 53, 53))
                                    .addGroup(jLayeredPanePlačiloLayout.createSequentialGroup()
                                        .addComponent(jLabelStKartice)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldStKartice)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabelCCV)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jTextFieldCCV, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPanePlačiloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jLayeredPanePlačiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonPonastavi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIzvediPlacilo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(137, 137, 137))))
        );
        jLayeredPanePlačiloLayout.setVerticalGroup(
            jLayeredPanePlačiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPanePlačiloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPanePlačiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMoznostPlacila)
                    .addComponent(jRadioButtonGotovina)
                    .addComponent(jRadioButtonKartica))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPanePlačiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStKartice)
                    .addComponent(jTextFieldStKartice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCCV)
                    .addComponent(jTextFieldCCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPaneZnesek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonIzvediPlacilo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPonastavi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelStatus.setText("Status:");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPaneOseba)
                    .addComponent(jLayeredPaneAvtomobil))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPanePlačilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jLabelStatus)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLayeredPaneAvtomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPaneOseba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPanePlačilo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabelStatus))
        );

        jMenuDatoteka.setMnemonic('D');
        jMenuDatoteka.setText("Datoteka");

        jMenuItemOdpri.setMnemonic('O');
        jMenuItemOdpri.setText("Odpri");
        jMenuDatoteka.add(jMenuItemOdpri);

        jMenuItemShrani.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemShrani.setMnemonic('S');
        jMenuItemShrani.setText("Shrani");
        jMenuDatoteka.add(jMenuItemShrani);

        jMenuItemIzhod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemIzhod.setMnemonic('I');
        jMenuItemIzhod.setText("Izhod");
        jMenuDatoteka.add(jMenuItemIzhod);

        jMenuBarMain.add(jMenuDatoteka);

        jMenuUredi.setMnemonic('U');
        jMenuUredi.setText("Uredi");

        jMenuItem4.setMnemonic('P');
        jMenuItem4.setText("Ponastavi");
        jMenuUredi.add(jMenuItem4);

        jMenuBarMain.add(jMenuUredi);

        jMenuPomoc.setMnemonic('P');
        jMenuPomoc.setText("Pomoč");

        jMenuItemAvtor.setMnemonic('A');
        jMenuItemAvtor.setText("Avtor");
        jMenuPomoc.add(jMenuItemAvtor);

        jMenuBarMain.add(jMenuPomoc);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logjMenuBarMainl.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzvediPlacilo;
    private javax.swing.JButton jButtonPonastavi;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JComboBox<String> jComboBoxIzbiraAvtomobila;
    private javax.swing.JComboBox<String> jComboBoxMestoOddaje;
    private javax.swing.JComboBox<String> jComboBoxPrevzemnoMesto;
    private javax.swing.JLabel jLabelCCV;
    private javax.swing.JLabel jLabelDatumIzposoje;
    private javax.swing.JLabel jLabelDatumOddaje;
    private javax.swing.JLabel jLabelDnesvniZnesek;
    private javax.swing.JLabel jLabelDnevnaNajemnina;
    private javax.swing.JLabel jLabelDodatnoZav;
    private javax.swing.JLabel jLabelEposta;
    private javax.swing.JLabel jLabelImeOsebe;
    private javax.swing.JLabel jLabelIzbiraAvtomobila;
    private javax.swing.JLabel jLabelIzbiraMenjalnika;
    private javax.swing.JLabel jLabelIzkusnje;
    private javax.swing.JLabel jLabelKrajOsebe;
    private javax.swing.JLabel jLabelMestoOddaje;
    private javax.swing.JLabel jLabelMoznostPlacila;
    private javax.swing.JLabel jLabelPostnaSt;
    private javax.swing.JLabel jLabelPrevzemnoMesto;
    private javax.swing.JLabel jLabelPriimekOsebe;
    private javax.swing.JLabel jLabelSkupnaNajemnina;
    private javax.swing.JLabel jLabelSkupniZnesek;
    private javax.swing.JLabel jLabelStKartice;
    private javax.swing.JLabel jLabelStarostOsebe;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTelefonOsebe;
    private javax.swing.JLabel jLabelUlicaOsebe;
    private javax.swing.JLabel jLabelVelikostAvtomobila;
    private javax.swing.JLabel jLabelVrstaMotorja;
    private javax.swing.JLayeredPane jLayeredPaneAvtomobil;
    private javax.swing.JLayeredPane jLayeredPaneOseba;
    private javax.swing.JLayeredPane jLayeredPanePlačilo;
    private javax.swing.JLayeredPane jLayeredPaneZnesek;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuDatoteka;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAvtor;
    private javax.swing.JMenuItem jMenuItemIzhod;
    private javax.swing.JMenuItem jMenuItemOdpri;
    private javax.swing.JMenuItem jMenuItemShrani;
    private javax.swing.JMenu jMenuPomoc;
    private javax.swing.JMenu jMenuUredi;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JRadioButton jRadioButtonDodatnoDa;
    private javax.swing.JRadioButton jRadioButtonDodatnoNe;
    private javax.swing.JRadioButton jRadioButtonGotovina;
    private javax.swing.JRadioButton jRadioButtonKartica;
    private javax.swing.JRadioButton jRadioButtonMenjalnikAvtomatski;
    private javax.swing.JRadioButton jRadioButtonMenjalnikRočni;
    private javax.swing.JRadioButton jRadioButtonMotorBencinski;
    private javax.swing.JRadioButton jRadioButtonMotorDizelski;
    private javax.swing.JRadioButton jRadioButtonVelikostMajhen;
    private javax.swing.JRadioButton jRadioButtonVelikostSrednji;
    private javax.swing.JRadioButton jRadioButtonVelikostVelik;
    private javax.swing.JSpinner jSpinnerIzkusnje;
    private javax.swing.JSpinner jSpinnerStarost;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldCCV;
    private javax.swing.JTextField jTextFieldStKartice;
    // End of variables declaration//GEN-END:variables
}
