/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naloga3;

import java.awt.Component;
import java.awt.Container;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author tilen
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    private void fillDates() {
        
        for(int i = 1900; i < 2020; i++) {
            jComboBoxYear.addItem(Integer.toString(i));
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupIzkusnje = new javax.swing.ButtonGroup();
        buttonGroupVrstaVozila = new javax.swing.ButtonGroup();
        buttonGroupZavarovanje = new javax.swing.ButtonGroup();
        buttonGroupKasko = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPaneZavarovanec = new javax.swing.JLayeredPane();
        jLabelIme = new javax.swing.JLabel();
        jLabelPriimek = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPriimek = new javax.swing.JTextField();
        jLabelDatum = new javax.swing.JLabel();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jComboBoxYear = new javax.swing.JComboBox<>();
        fillDates();
        jLabelKraj = new javax.swing.JLabel();
        jLabelUlica = new javax.swing.JLabel();
        jTextFieldKraj = new javax.swing.JTextField();
        jTextFieldUlica = new javax.swing.JTextField();
        jLabelPosta = new javax.swing.JLabel();
        jLabelHisa = new javax.swing.JLabel();
        jTextFieldPosta = new javax.swing.JTextField();
        jTextFieldHisa = new javax.swing.JTextField();
        jLabelIzkusnje = new javax.swing.JLabel();
        jRadioButtonMlad = new javax.swing.JRadioButton();
        jRadioButtonIzkusen = new javax.swing.JRadioButton();
        jLayeredPaneVozilo = new javax.swing.JLayeredPane();
        jLabelZnamka = new javax.swing.JLabel();
        jLabelOznaka = new javax.swing.JLabel();
        jLabelGorivo = new javax.swing.JLabel();
        jLabelMoc = new javax.swing.JLabel();
        jTextFieldZnamka = new javax.swing.JTextField();
        jTextFieldOznaka = new javax.swing.JTextField();
        jTextFieldGorivo = new javax.swing.JTextField();
        jTextFieldMoc = new javax.swing.JTextField();
        jLabelBarva = new javax.swing.JLabel();
        jTextFieldBarva = new javax.swing.JTextField();
        jLabelSedezi = new javax.swing.JLabel();
        jLabelProstornina = new javax.swing.JLabel();
        jTextFieldProstornina = new javax.swing.JTextField();
        jLayeredPaneVrstaVozila = new javax.swing.JLayeredPane();
        jRadioButtonOsebniAvto = new javax.swing.JRadioButton();
        jRadioButtonMotor = new javax.swing.JRadioButton();
        jRadioButtonAvtobus = new javax.swing.JRadioButton();
        jRadioButtonTovornjak = new javax.swing.JRadioButton();
        jRadioButtonTraktor = new javax.swing.JRadioButton();
        jTextFieldSedezi = new javax.swing.JTextField();
        jLayeredPaneRegistracija = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldLetoRegistracije = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDanRegistracije = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldKrajRegistracije = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRegistrskaOznacba = new javax.swing.JTextField();
        jLayeredPaneZavarovanje = new javax.swing.JLayeredPane();
        jLabelOsnovnoZavarovanje = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLayeredPaneDodatnoZavarovanje = new javax.swing.JLayeredPane();
        jCheckBoxZavSteklo = new javax.swing.JCheckBox();
        jCheckBoxZavParking = new javax.swing.JCheckBox();
        jCheckBoxZavPotniki = new javax.swing.JCheckBox();
        jCheckBoxZavTretjeOsebe = new javax.swing.JCheckBox();
        jCheckBoxZavGum = new javax.swing.JCheckBox();
        jCheckBoxZavKraja = new javax.swing.JCheckBox();
        jCheckBoxZavToca = new javax.swing.JCheckBox();
        jButtonPobrisi = new javax.swing.JButton();
        jButtonShrani = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikacija za zavarovanje avtomobilov");

        jLayeredPaneZavarovanec.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki o zavarovancu"));
        jLayeredPaneZavarovanec.setToolTipText("");

        jLabelIme.setText("Ime:");

        jLabelPriimek.setText("Priimek:");

        jLabelDatum.setText("Rojstni datum:");

        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "januar", "februar", "marec", "april", "maj", "junij", "julij", "august", "september", "oktober", "november", "december" }));

        jLabelKraj.setText("Kraj:");

        jLabelUlica.setText("Ulica:");

        jLabelPosta.setText("Poštna št.:");

        jLabelHisa.setText("Hišna št.:");

        jTextFieldPosta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                postaFocusLost(evt);
            }
        });

        jLabelIzkusnje.setText("Izkušnje:");

        buttonGroupIzkusnje.add(jRadioButtonMlad);
        jRadioButtonMlad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonMlad.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButtonMlad.setText("Mlad voznik");

        buttonGroupIzkusnje.add(jRadioButtonIzkusen);
        jRadioButtonIzkusen.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonIzkusen.setSelected(true);
        jRadioButtonIzkusen.setText("Izkušen voznik");

        jLayeredPaneZavarovanec.setLayer(jLabelIme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jLabelPriimek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jTextFieldIme, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jTextFieldPriimek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jLabelDatum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jComboBoxMonth, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jComboBoxYear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jLabelKraj, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jLabelUlica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jTextFieldKraj, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jTextFieldUlica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jLabelPosta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jLabelHisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jTextFieldPosta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jTextFieldHisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jLabelIzkusnje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jRadioButtonMlad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanec.setLayer(jRadioButtonIzkusen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneZavarovanecLayout = new javax.swing.GroupLayout(jLayeredPaneZavarovanec);
        jLayeredPaneZavarovanec.setLayout(jLayeredPaneZavarovanecLayout);
        jLayeredPaneZavarovanecLayout.setHorizontalGroup(
            jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneZavarovanecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPaneZavarovanecLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIme)
                            .addComponent(jLabelPriimek))
                        .addGap(21, 21, 21)
                        .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPriimek, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jTextFieldIme))
                        .addGap(31, 31, 31)
                        .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUlica)
                            .addComponent(jLabelKraj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUlica, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jTextFieldKraj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPosta)
                            .addComponent(jLabelHisa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPosta)
                            .addComponent(jTextFieldHisa)))
                    .addGroup(jLayeredPaneZavarovanecLayout.createSequentialGroup()
                        .addComponent(jLabelDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelIzkusnje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonMlad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonIzkusen)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPaneZavarovanecLayout.setVerticalGroup(
            jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneZavarovanecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIme)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelKraj)
                    .addComponent(jTextFieldKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPosta)
                    .addComponent(jTextFieldPosta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPriimek)
                    .addComponent(jTextFieldPriimek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUlica)
                    .addComponent(jTextFieldUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHisa)
                    .addComponent(jTextFieldHisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneZavarovanecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatum)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelIzkusnje)
                    .addComponent(jRadioButtonMlad)
                    .addComponent(jRadioButtonIzkusen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPaneVozilo.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki o vozilu"));
        jLayeredPaneVozilo.setToolTipText("");

        jLabelZnamka.setText("Znamka:");

        jLabelOznaka.setText("Oznaka:");

        jLabelGorivo.setText("Gorivo:");

        jLabelMoc.setText("Moč (kW):");

        jLabelBarva.setText("Barva:");

        jLabelSedezi.setText("Št. sedežev:");

        jLabelProstornina.setText("Prostornina:");

        jLayeredPaneVrstaVozila.setBorder(javax.swing.BorderFactory.createTitledBorder("Vrsta vozila"));

        buttonGroupVrstaVozila.add(jRadioButtonOsebniAvto);
        jRadioButtonOsebniAvto.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonOsebniAvto.setSelected(true);
        jRadioButtonOsebniAvto.setText("Osebni avto");

        buttonGroupVrstaVozila.add(jRadioButtonMotor);
        jRadioButtonMotor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonMotor.setText("Motor");

        buttonGroupVrstaVozila.add(jRadioButtonAvtobus);
        jRadioButtonAvtobus.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonAvtobus.setText("Avtobus");

        buttonGroupVrstaVozila.add(jRadioButtonTovornjak);
        jRadioButtonTovornjak.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonTovornjak.setText("Tovornjak");

        buttonGroupVrstaVozila.add(jRadioButtonTraktor);
        jRadioButtonTraktor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButtonTraktor.setText("Traktor");

        jLayeredPaneVrstaVozila.setLayer(jRadioButtonOsebniAvto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVrstaVozila.setLayer(jRadioButtonMotor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVrstaVozila.setLayer(jRadioButtonAvtobus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVrstaVozila.setLayer(jRadioButtonTovornjak, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVrstaVozila.setLayer(jRadioButtonTraktor, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneVrstaVozilaLayout = new javax.swing.GroupLayout(jLayeredPaneVrstaVozila);
        jLayeredPaneVrstaVozila.setLayout(jLayeredPaneVrstaVozilaLayout);
        jLayeredPaneVrstaVozilaLayout.setHorizontalGroup(
            jLayeredPaneVrstaVozilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneVrstaVozilaLayout.createSequentialGroup()
                .addGroup(jLayeredPaneVrstaVozilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonOsebniAvto)
                    .addComponent(jRadioButtonMotor)
                    .addComponent(jRadioButtonAvtobus)
                    .addComponent(jRadioButtonTovornjak)
                    .addComponent(jRadioButtonTraktor))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jLayeredPaneVrstaVozilaLayout.setVerticalGroup(
            jLayeredPaneVrstaVozilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneVrstaVozilaLayout.createSequentialGroup()
                .addComponent(jRadioButtonOsebniAvto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonMotor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonAvtobus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTovornjak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTraktor)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jLayeredPaneVozilo.setLayer(jLabelZnamka, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jLabelOznaka, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jLabelGorivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jLabelMoc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jTextFieldZnamka, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jTextFieldOznaka, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jTextFieldGorivo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jTextFieldMoc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jLabelBarva, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jTextFieldBarva, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jLabelSedezi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jLabelProstornina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jTextFieldProstornina, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jLayeredPaneVrstaVozila, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneVozilo.setLayer(jTextFieldSedezi, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneVoziloLayout = new javax.swing.GroupLayout(jLayeredPaneVozilo);
        jLayeredPaneVozilo.setLayout(jLayeredPaneVoziloLayout);
        jLayeredPaneVoziloLayout.setHorizontalGroup(
            jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneVoziloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelZnamka)
                    .addComponent(jLabelOznaka)
                    .addComponent(jLabelGorivo)
                    .addComponent(jLabelMoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldZnamka)
                    .addComponent(jTextFieldOznaka)
                    .addComponent(jTextFieldGorivo)
                    .addComponent(jTextFieldMoc, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBarva)
                    .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldBarva, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jLayeredPaneVoziloLayout.createSequentialGroup()
                            .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneVoziloLayout.createSequentialGroup()
                                    .addComponent(jLabelProstornina)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jLayeredPaneVoziloLayout.createSequentialGroup()
                                    .addComponent(jLabelSedezi)
                                    .addGap(16, 16, 16)))
                            .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldProstornina)
                                .addComponent(jTextFieldSedezi, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))))
                .addGap(55, 55, 55)
                .addComponent(jLayeredPaneVrstaVozila)
                .addContainerGap())
        );
        jLayeredPaneVoziloLayout.setVerticalGroup(
            jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneVoziloLayout.createSequentialGroup()
                .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPaneVrstaVozila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPaneVoziloLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelZnamka)
                            .addComponent(jTextFieldZnamka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBarva)
                            .addComponent(jTextFieldBarva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProstornina)
                            .addComponent(jTextFieldProstornina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOznaka)
                            .addComponent(jTextFieldOznaka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGorivo)
                            .addComponent(jTextFieldGorivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSedezi)
                            .addComponent(jTextFieldSedezi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPaneVoziloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMoc)
                            .addComponent(jTextFieldMoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPaneRegistracija.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki o registraciji"));

        jLabel1.setText("Mesec prve registracije:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "januar", "februar", "marec", "april", "maj", "junij", "julij", "avgust", "september", "oktober", "november", "december" }));

        jLabel2.setText("Leto prve registracije:");

        jLabel3.setText("Dan prve registracije:");

        jLabel4.setText("Kraj prve registracije:");

        jLabel5.setText("Registrska označba:");

        jLayeredPaneRegistracija.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRegistracija.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRegistracija.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRegistracija.setLayer(jTextFieldLetoRegistracije, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRegistracija.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRegistracija.setLayer(jTextFieldDanRegistracije, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRegistracija.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRegistracija.setLayer(jTextFieldKrajRegistracije, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRegistracija.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneRegistracija.setLayer(jTextFieldRegistrskaOznacba, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneRegistracijaLayout = new javax.swing.GroupLayout(jLayeredPaneRegistracija);
        jLayeredPaneRegistracija.setLayout(jLayeredPaneRegistracijaLayout);
        jLayeredPaneRegistracijaLayout.setHorizontalGroup(
            jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPaneRegistracijaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLetoRegistracije)
                    .addComponent(jTextFieldRegistrskaOznacba, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldDanRegistracije)
                    .addComponent(jTextFieldKrajRegistracije, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPaneRegistracijaLayout.setVerticalGroup(
            jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneRegistracijaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldDanRegistracije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPaneRegistracijaLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldLetoRegistracije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldKrajRegistracije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPaneRegistracijaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldRegistrskaOznacba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPaneZavarovanje.setBorder(javax.swing.BorderFactory.createTitledBorder("Podatki o zavarovanju"));

        jLabelOsnovnoZavarovanje.setText("Osnovno Zavarovanje:");

        buttonGroupZavarovanje.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("AO");

        buttonGroupZavarovanje.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton2.setText("AO+");

        jLabel6.setText("Kasko:");

        buttonGroupKasko.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton3.setText("Polno");

        buttonGroupKasko.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton4.setText("Odbitna franšiza");

        buttonGroupKasko.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Brez");

        jLayeredPaneDodatnoZavarovanje.setBorder(javax.swing.BorderFactory.createTitledBorder("Dodatno zavarovanje"));

        jCheckBoxZavSteklo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxZavSteklo.setText("Zavarovanje stekel");

        jCheckBoxZavParking.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxZavParking.setText("Zavarovanje na parkirišču");

        jCheckBoxZavPotniki.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxZavPotniki.setText("Zavarovanje potnikov");

        jCheckBoxZavTretjeOsebe.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxZavTretjeOsebe.setText("Zavarovanje tretje osebe");

        jCheckBoxZavGum.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxZavGum.setText("Zavarovanje gum");

        jCheckBoxZavKraja.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxZavKraja.setText("Zavarovanje proti kraji");

        jCheckBoxZavToca.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxZavToca.setText("Zavarovanje proti toči");

        jLayeredPaneDodatnoZavarovanje.setLayer(jCheckBoxZavSteklo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDodatnoZavarovanje.setLayer(jCheckBoxZavParking, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDodatnoZavarovanje.setLayer(jCheckBoxZavPotniki, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDodatnoZavarovanje.setLayer(jCheckBoxZavTretjeOsebe, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDodatnoZavarovanje.setLayer(jCheckBoxZavGum, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDodatnoZavarovanje.setLayer(jCheckBoxZavKraja, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneDodatnoZavarovanje.setLayer(jCheckBoxZavToca, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneDodatnoZavarovanjeLayout = new javax.swing.GroupLayout(jLayeredPaneDodatnoZavarovanje);
        jLayeredPaneDodatnoZavarovanje.setLayout(jLayeredPaneDodatnoZavarovanjeLayout);
        jLayeredPaneDodatnoZavarovanjeLayout.setHorizontalGroup(
            jLayeredPaneDodatnoZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneDodatnoZavarovanjeLayout.createSequentialGroup()
                .addGroup(jLayeredPaneDodatnoZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxZavTretjeOsebe)
                    .addGroup(jLayeredPaneDodatnoZavarovanjeLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneDodatnoZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxZavParking)
                            .addComponent(jCheckBoxZavSteklo)
                            .addComponent(jCheckBoxZavPotniki))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPaneDodatnoZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxZavToca)
                            .addComponent(jCheckBoxZavGum)
                            .addComponent(jCheckBoxZavKraja))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPaneDodatnoZavarovanjeLayout.setVerticalGroup(
            jLayeredPaneDodatnoZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneDodatnoZavarovanjeLayout.createSequentialGroup()
                .addGroup(jLayeredPaneDodatnoZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxZavSteklo)
                    .addComponent(jCheckBoxZavGum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPaneDodatnoZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxZavParking)
                    .addComponent(jCheckBoxZavKraja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPaneDodatnoZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxZavPotniki)
                    .addComponent(jCheckBoxZavToca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBoxZavTretjeOsebe))
        );

        jButtonPobrisi.setText("Ponastavi vnose");
        jButtonPobrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponastaviVnose(evt);
            }
        });

        jButtonShrani.setText("Shrani vnos");

        jLayeredPaneZavarovanje.setLayer(jLabelOsnovnoZavarovanje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanje.setLayer(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanje.setLayer(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanje.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanje.setLayer(jRadioButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanje.setLayer(jRadioButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanje.setLayer(jRadioButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanje.setLayer(jLayeredPaneDodatnoZavarovanje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanje.setLayer(jButtonPobrisi, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPaneZavarovanje.setLayer(jButtonShrani, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPaneZavarovanjeLayout = new javax.swing.GroupLayout(jLayeredPaneZavarovanje);
        jLayeredPaneZavarovanje.setLayout(jLayeredPaneZavarovanjeLayout);
        jLayeredPaneZavarovanjeLayout.setHorizontalGroup(
            jLayeredPaneZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneZavarovanjeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPaneZavarovanjeLayout.createSequentialGroup()
                        .addGroup(jLayeredPaneZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPaneZavarovanjeLayout.createSequentialGroup()
                                .addComponent(jLabelOsnovnoZavarovanje)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2))
                            .addGroup(jLayeredPaneZavarovanjeLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jLayeredPaneZavarovanjeLayout.createSequentialGroup()
                        .addComponent(jLayeredPaneDodatnoZavarovanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jLayeredPaneZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPobrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonShrani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(54, 54, 54))))
        );
        jLayeredPaneZavarovanjeLayout.setVerticalGroup(
            jLayeredPaneZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPaneZavarovanjeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPaneZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOsnovnoZavarovanje)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPaneZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jLayeredPaneZavarovanjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPaneZavarovanjeLayout.createSequentialGroup()
                        .addComponent(jButtonPobrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonShrani)
                        .addGap(6, 6, 6))
                    .addComponent(jLayeredPaneDodatnoZavarovanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPaneZavarovanec)
                    .addComponent(jLayeredPaneVozilo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPaneRegistracija)
                    .addComponent(jLayeredPaneZavarovanje))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPaneRegistracija)
                    .addComponent(jLayeredPaneZavarovanec))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPaneVozilo)
                    .addComponent(jLayeredPaneZavarovanje))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelStatus.setText("Status: ");

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setMnemonic('D');
        jMenu1.setText("Datoteka");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setMnemonic('S');
        jMenuItem2.setText("Shrani");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setMnemonic('I');
        jMenuItem3.setText("Izhod");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izhodCB(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('U');
        jMenu2.setText("Uredi");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setMnemonic('P');
        jMenuItem1.setText("Ponastavi");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponastaviVnose(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setMnemonic('R');
        jMenuItem5.setText("Razveljavi");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('P');
        jMenu3.setText("Pomoč");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setMnemonic('A');
        jMenuItem4.setText("Avtor");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avtorCB(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatus))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelStatus))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ponastaviVnose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponastaviVnose
        
        jTextFieldBarva.setText("");
        jTextFieldDanRegistracije.setText("");
        jTextFieldGorivo.setText("");
        jTextFieldHisa.setText("");
        jTextFieldIme.setText("");
        jTextFieldKraj.setText("");
        jTextFieldKrajRegistracije.setText("");
        jTextFieldLetoRegistracije.setText("");
        jTextFieldMoc.setText("");
        jTextFieldOznaka.setText("");
        jTextFieldPosta.setText("");
        jTextFieldPriimek.setText("");
        jTextFieldProstornina.setText("");
        jTextFieldRegistrskaOznacba.setText("");
        jTextFieldSedezi.setText("");
        jTextFieldUlica.setText("");
        jTextFieldZnamka.setText("");
        
        jCheckBoxZavGum.setSelected(false);
        jCheckBoxZavKraja.setSelected(false);
        jCheckBoxZavParking.setSelected(false);
        jCheckBoxZavPotniki.setSelected(false);
        jCheckBoxZavSteklo.setSelected(false);
        jCheckBoxZavToca.setSelected(false);
        jCheckBoxZavTretjeOsebe.setSelected(false);
        
        jLabelStatus.setText("Status: Vnosi pobrisani");
    }//GEN-LAST:event_ponastaviVnose

    private void izhodCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izhodCB
     
        System.exit(0);
        
    }//GEN-LAST:event_izhodCB

    private void avtorCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avtorCB
    
        JOptionPane.showMessageDialog(this, "Avtor: Tilen Berlak", "Avtor", JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_avtorCB

    private void postaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_postaFocusLost
        
        String text = jTextFieldPosta.getText();
        
        if(!text.matches("[0-9]+") && text.length() > 2) {
             JOptionPane.showMessageDialog(this, "Poštna številka " + text + " je neveljavna.", "Opozorilo", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_postaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupIzkusnje;
    private javax.swing.ButtonGroup buttonGroupKasko;
    private javax.swing.ButtonGroup buttonGroupVrstaVozila;
    private javax.swing.ButtonGroup buttonGroupZavarovanje;
    private javax.swing.JButton jButtonPobrisi;
    private javax.swing.JButton jButtonShrani;
    private javax.swing.JCheckBox jCheckBoxZavGum;
    private javax.swing.JCheckBox jCheckBoxZavKraja;
    private javax.swing.JCheckBox jCheckBoxZavParking;
    private javax.swing.JCheckBox jCheckBoxZavPotniki;
    private javax.swing.JCheckBox jCheckBoxZavSteklo;
    private javax.swing.JCheckBox jCheckBoxZavToca;
    private javax.swing.JCheckBox jCheckBoxZavTretjeOsebe;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JComboBox<String> jComboBoxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBarva;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JLabel jLabelGorivo;
    private javax.swing.JLabel jLabelHisa;
    private javax.swing.JLabel jLabelIme;
    private javax.swing.JLabel jLabelIzkusnje;
    private javax.swing.JLabel jLabelKraj;
    private javax.swing.JLabel jLabelMoc;
    private javax.swing.JLabel jLabelOsnovnoZavarovanje;
    private javax.swing.JLabel jLabelOznaka;
    private javax.swing.JLabel jLabelPosta;
    private javax.swing.JLabel jLabelPriimek;
    private javax.swing.JLabel jLabelProstornina;
    private javax.swing.JLabel jLabelSedezi;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelUlica;
    private javax.swing.JLabel jLabelZnamka;
    private javax.swing.JLayeredPane jLayeredPaneDodatnoZavarovanje;
    private javax.swing.JLayeredPane jLayeredPaneRegistracija;
    private javax.swing.JLayeredPane jLayeredPaneVozilo;
    private javax.swing.JLayeredPane jLayeredPaneVrstaVozila;
    private javax.swing.JLayeredPane jLayeredPaneZavarovanec;
    private javax.swing.JLayeredPane jLayeredPaneZavarovanje;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButtonAvtobus;
    private javax.swing.JRadioButton jRadioButtonIzkusen;
    private javax.swing.JRadioButton jRadioButtonMlad;
    private javax.swing.JRadioButton jRadioButtonMotor;
    private javax.swing.JRadioButton jRadioButtonOsebniAvto;
    private javax.swing.JRadioButton jRadioButtonTovornjak;
    private javax.swing.JRadioButton jRadioButtonTraktor;
    private javax.swing.JTextField jTextFieldBarva;
    private javax.swing.JTextField jTextFieldDanRegistracije;
    private javax.swing.JTextField jTextFieldGorivo;
    private javax.swing.JTextField jTextFieldHisa;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldKraj;
    private javax.swing.JTextField jTextFieldKrajRegistracije;
    private javax.swing.JTextField jTextFieldLetoRegistracije;
    private javax.swing.JTextField jTextFieldMoc;
    private javax.swing.JTextField jTextFieldOznaka;
    private javax.swing.JTextField jTextFieldPosta;
    private javax.swing.JTextField jTextFieldPriimek;
    private javax.swing.JTextField jTextFieldProstornina;
    private javax.swing.JTextField jTextFieldRegistrskaOznacba;
    private javax.swing.JTextField jTextFieldSedezi;
    private javax.swing.JTextField jTextFieldUlica;
    private javax.swing.JTextField jTextFieldZnamka;
    // End of variables declaration//GEN-END:variables
}
