/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naloga2;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author tilen
 */
public class BesediloOkvir extends javax.swing.JFrame {

    /**
     * Creates new form BesediloOkvir
     */
    public BesediloOkvir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfc = new javax.swing.JFileChooser();
        jPanelMain = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jToolBarMain = new javax.swing.JToolBar();
        jButtonOdpri = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonShrani = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonNajdi = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButtonPomoc = new javax.swing.JButton();
        jTextFieldIskanje = new javax.swing.JTextField();
        jTextFieldZamenjaj = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuDatoteka = new javax.swing.JMenu();
        jMenuItemOdpri = new javax.swing.JMenuItem();
        jMenuItemShrani = new javax.swing.JMenuItem();
        jMenuItemIzhod = new javax.swing.JMenuItem();
        jMenuIskanje = new javax.swing.JMenu();
        jMenuItemNajdi = new javax.swing.JMenuItem();
        jMenuItemZamenjaj = new javax.swing.JMenuItem();
        jMenuBarve = new javax.swing.JMenu();
        jMenuItemBesedilo = new javax.swing.JMenuItem();
        jMenuItemPodlaga = new javax.swing.JMenuItem();
        jMenuPomoc = new javax.swing.JMenu();
        jMenuItemAvtor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelStatus.setText("Status:");

        jToolBarMain.setFloatable(false);
        jToolBarMain.setRollover(true);

        jButtonOdpri.setText("Odpri");
        jButtonOdpri.setFocusable(false);
        jButtonOdpri.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonOdpri.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonOdpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdpriCB(evt);
            }
        });
        jToolBarMain.add(jButtonOdpri);
        jToolBarMain.add(jSeparator1);

        jButtonShrani.setText("Shrani");
        jButtonShrani.setFocusable(false);
        jButtonShrani.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonShrani.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonShrani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShraniCB(evt);
            }
        });
        jToolBarMain.add(jButtonShrani);
        jToolBarMain.add(jSeparator2);

        jButtonNajdi.setText("Najdi vse");
        jButtonNajdi.setFocusable(false);
        jButtonNajdi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNajdi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNajdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                najdiCB(evt);
            }
        });
        jToolBarMain.add(jButtonNajdi);
        jToolBarMain.add(jSeparator3);

        jButtonPomoc.setText("Zamenjaj vse");
        jButtonPomoc.setFocusable(false);
        jButtonPomoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPomoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonPomoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamenjajCB(evt);
            }
        });
        jToolBarMain.add(jButtonPomoc);

        jLabel2.setText("Iskani niz:");

        jLabel3.setText("Zamenjaj z:");

        jScrollPane1.setViewportView(jTextPane1);

        jLabel4.setText("Datoteka:");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarMain, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addComponent(jLabelStatus)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIskanje)
                            .addComponent(jTextFieldZamenjaj)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                .addComponent(jToolBarMain, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldIskanje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldZamenjaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatus))
        );

        getContentPane().add(jPanelMain, java.awt.BorderLayout.CENTER);

        jMenuDatoteka.setMnemonic('D');
        jMenuDatoteka.setText("Datoteka");

        jMenuItemOdpri.setMnemonic('O');
        jMenuItemOdpri.setText("Odpri");
        jMenuItemOdpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdpriCB(evt);
            }
        });
        jMenuDatoteka.add(jMenuItemOdpri);

        jMenuItemShrani.setMnemonic('S');
        jMenuItemShrani.setText("Shrani");
        jMenuItemShrani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShraniCB(evt);
            }
        });
        jMenuDatoteka.add(jMenuItemShrani);

        jMenuItemIzhod.setMnemonic('I');
        jMenuItemIzhod.setText("Izhod");
        jMenuItemIzhod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzhodCB(evt);
            }
        });
        jMenuDatoteka.add(jMenuItemIzhod);

        jMenuBarMain.add(jMenuDatoteka);

        jMenuIskanje.setMnemonic('I');
        jMenuIskanje.setText("Iskanje");

        jMenuItemNajdi.setMnemonic('N');
        jMenuItemNajdi.setText("Najdi vse");
        jMenuItemNajdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                najdiCB(evt);
            }
        });
        jMenuIskanje.add(jMenuItemNajdi);

        jMenuItemZamenjaj.setMnemonic('Z');
        jMenuItemZamenjaj.setText("Zamenjaj vse");
        jMenuItemZamenjaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zamenjajCB(evt);
            }
        });
        jMenuIskanje.add(jMenuItemZamenjaj);

        jMenuBarMain.add(jMenuIskanje);

        jMenuBarve.setMnemonic('B');
        jMenuBarve.setText("Barve");

        jMenuItemBesedilo.setMnemonic('B');
        jMenuItemBesedilo.setText("Besedilo");
        jMenuItemBesedilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barvajBesediloCB(evt);
            }
        });
        jMenuBarve.add(jMenuItemBesedilo);

        jMenuItemPodlaga.setMnemonic('P');
        jMenuItemPodlaga.setText("Podlaga");
        jMenuItemPodlaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barvajPodlagoCB(evt);
            }
        });
        jMenuBarve.add(jMenuItemPodlaga);

        jMenuBarMain.add(jMenuBarve);

        jMenuPomoc.setMnemonic('P');
        jMenuPomoc.setText("Pomoč");

        jMenuItemAvtor.setMnemonic('A');
        jMenuItemAvtor.setText("Avtor");
        jMenuItemAvtor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avtorCB(evt);
            }
        });
        jMenuPomoc.add(jMenuItemAvtor);

        jMenuBarMain.add(jMenuPomoc);

        setJMenuBar(jMenuBarMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OdpriCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdpriCB
       
        if(jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            jLabel4.setText("Datoteka: " + f.getName());
            try {
                jTextPane1.read(new FileReader(f), null);
                jLabelStatus.setText("Odprta datoteka: " + f.getName() + "  " + f.length() + "B");
            } catch (Exception e) {
                jLabelStatus.setText("Napaka pri branju datoteke: " + f.getName());
            }
  
        }
        
    }//GEN-LAST:event_OdpriCB

    private void IzhodCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzhodCB
        System.exit(0);
    }//GEN-LAST:event_IzhodCB

    private void ShraniCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShraniCB
        
        if(jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            jLabel4.setText("Datoteka: " + f.getName());
            try {
                jTextPane1.write(new FileWriter(f));
                jLabelStatus.setText("Datoteka je shranjena");
            } catch (Exception e) {
                jLabelStatus.setText("Napaka pri shranjevanju datoteke: " + f.getName());
            }
        }    
    }//GEN-LAST:event_ShraniCB

    private void barvajBesediloCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barvajBesediloCB
        
        Color c = JColorChooser.showDialog(this, "Izberi barvo ospredja", Color.yellow);
        StyledDocument d = jTextPane1.getStyledDocument();
        Style s = jTextPane1.addStyle("barva ospredja", null);
        StyleConstants.setForeground(s, c);
        
        d.setCharacterAttributes(jTextPane1.getSelectionStart(), jTextPane1.getSelectionEnd() - jTextPane1.getSelectionStart(), s, false);
        
    }//GEN-LAST:event_barvajBesediloCB

    private void barvajPodlagoCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barvajPodlagoCB
        
        Color c = JColorChooser.showDialog(this, "Izberi barvo ozadja", Color.yellow);
        StyledDocument d = jTextPane1.getStyledDocument();
        Style s = jTextPane1.addStyle("barva ozadja", null);
        StyleConstants.setBackground(s, c);
        
        d.setCharacterAttributes(jTextPane1.getSelectionStart(), jTextPane1.getSelectionEnd() - jTextPane1.getSelectionStart(), s, false);
    }//GEN-LAST:event_barvajPodlagoCB

    private void najdiCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_najdiCB
        
        String iskanje = jTextFieldIskanje.getText();
        
        int i = jTextPane1.getText().indexOf(iskanje);
        if(i == -1) {
            jLabelStatus.setText("Iskani niz ne obstaja");       
        }
           
        i = jTextPane1.getText().indexOf(iskanje);
        jTextPane1.select(i, i+iskanje.length());

        StyledDocument d = jTextPane1.getStyledDocument();
        Style s = jTextPane1.addStyle("barva ozadja", null);
        StyleConstants.setBackground(s, Color.yellow);

        d.setCharacterAttributes(jTextPane1.getSelectionStart(), jTextPane1.getSelectionEnd() - jTextPane1.getSelectionStart(), s, false);
        jLabelStatus.setText("Iskani niz najden");
       
     
    }//GEN-LAST:event_najdiCB

    private void zamenjajCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zamenjajCB
        String iskanje = jTextFieldIskanje.getText();
        
        int i = jTextPane1.getText().indexOf(iskanje);
        if(i == -1) {
            jLabelStatus.setText("Iskani niz ne obstaja");       
        }
        
        while(i != -1) {
            i = jTextPane1.getText().indexOf(iskanje);
            jTextPane1.select(i, i+iskanje.length());
            jTextPane1.replaceSelection(jTextFieldZamenjaj.getText());
            jLabelStatus.setText("Iskani niz zamenjan");
        }

    }//GEN-LAST:event_zamenjajCB

    private void avtorCB(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avtorCB
        jLabelStatus.setText("Avtor aplikacije: Tilen Berlak");
    }//GEN-LAST:event_avtorCB

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BesediloOkvir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BesediloOkvir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BesediloOkvir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BesediloOkvir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BesediloOkvir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNajdi;
    private javax.swing.JButton jButtonOdpri;
    private javax.swing.JButton jButtonPomoc;
    private javax.swing.JButton jButtonShrani;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenu jMenuBarve;
    private javax.swing.JMenu jMenuDatoteka;
    private javax.swing.JMenu jMenuIskanje;
    private javax.swing.JMenuItem jMenuItemAvtor;
    private javax.swing.JMenuItem jMenuItemBesedilo;
    private javax.swing.JMenuItem jMenuItemIzhod;
    private javax.swing.JMenuItem jMenuItemNajdi;
    private javax.swing.JMenuItem jMenuItemOdpri;
    private javax.swing.JMenuItem jMenuItemPodlaga;
    private javax.swing.JMenuItem jMenuItemShrani;
    private javax.swing.JMenuItem jMenuItemZamenjaj;
    private javax.swing.JMenu jMenuPomoc;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTextField jTextFieldIskanje;
    private javax.swing.JTextField jTextFieldZamenjaj;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToolBar jToolBarMain;
    private javax.swing.JFileChooser jfc;
    // End of variables declaration//GEN-END:variables
}
